[target.x86_64-unknown-linux-gnu] # Replace with your target
rustflags = [
    "-C", "target-feature=+avx,+avx2,+fma,+aes,+sse2,+bmi,+bmi2,+popcnt,+f16c",
    "-C", "llvm-args=-unroll-threshold=1000",
    "-C", "llvm-args=-vectorize-slp=true"
]
